" All of the plugins are installed with Vundle from this file.
source ~/.vim/config/plugins.vim

filetype plugin indent on     " required!

" VIM Configuration
source ~/.vim/config/config.vim

" Custom Functions
source ~/.vim/config/functions.vim

" VIM Mappings
source ~/.vim/config/mappings.vim

" Custom file settings
source ~/.vim/config/file_settings.vim

" Plugins configuration
source ~/.vim/config/plugins_config.vim

" Auto Commands
source ~/.vim/config/autocmds.vim
