_has(){
    command type "$1" > /dev/null 2>&1
}


if [[ `uname` == 'Darwin' ]]; then
    PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
    PATH="/usr/local/opt/python/libexec/bin:$PATH"
    MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
fi

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
#ZSH_THEME="spaceship"
ZSH_THEME="pnezis"

# Comment this out to disable weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# oh-my-zsh plugins to load
plugins=(git docker)

source $ZSH/oh-my-zsh.sh
#export SPACESHIP_KUBECONTEXT_SHOW=false
#export SPACESHIP_PROMPT_ADD_NEWLINE=false
#export SPACESHIP_PROMPT_ORDER=(time user dir host git elixir exec_time line_sep jobs exit_code char)

# Customize to your needs...

# Free up up Ctrl-S and Ctrl-Q for use with Vim:
stty -ixon -ixoff

# Set ls colors
eval `dircolors $HOME/.dircolors`

# Force tmux to assume that terminal supports 256 colors
alias tmux="tmux -2"
alias t="$HOME/dotfiles/bin/todo/todo.sh -d $HOME/dotfiles/bin/todo/todo.cfg"

# Switch to MacVim if in OsX
if [[ `uname` == 'Darwin' ]]; then
    alias vim="mvim -v"
fi

# Make vim default editor
export EDITOR="vim"

# Use Ctrl-Z to switch back to the last background job
# All credits here: http://sheerun.net/2014/03/21/how-to-boost-your-vim-productivity/?utm_source=hackernewsletter&utm_medium=email&utm_term=fav
fancy-ctrl-z () {
    if [[ $#BUFFER -eq 0 ]]; then
        BUFFER="fg"
        zle accept-line
    else
        zle push-input
        zle clear-screen
    fi
}

zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z

compctl -g '~/.itermocil/*(:t:r)' itermocil

# word navigations
if [[ `uname` == 'Darwin' ]]
then
    bindkey "^[^[[C" forward-word
    bindkey "^[^[[D" backward-word
fi

# Aliases
export WORKON_HOME=~/code/envs
source /usr/local/bin/virtualenvwrapper.sh

export GOPATH=$HOME/code/go
export LC_ALL=en_US.UTF-8

# Spark related configuraion
export SPARK_HOME=/usr/local/Cellar/apache-spark/2.2.0/libexec

# Hadoop configuration
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home
export HADOOP_VERSION=3.1.2
export HADOOP_HOME=/usr/local/Cellar/hadoop/3.1.2/libexec
export HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop/


PATH="$HADOOP_HOME/bin:$HADOOP_HOME/sbin:$GOPATH/bin:$SPARK_HOME/bin:$PATH"


# Alias ip to venv installed ipython
alias ip="python -c 'import IPython; IPython.terminal.ipapp.launch_new_instance()'"

# fzf via Homebrew
if [ -e /usr/local/opt/fzf/shell/completion.zsh ]; then
  source /usr/local/opt/fzf/shell/key-bindings.zsh
  source /usr/local/opt/fzf/shell/completion.zsh
fi

# fzf + ag configuration
if _has fzf && _has ag; then
  export FZF_DEFAULT_COMMAND='ag --nocolor -g ""'
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
  export FZF_ALT_C_COMMAND="$FZF_DEFAULT_COMMAND"
  export FZF_DEFAULT_OPTS='
  --color fg:242,bg:236,hl:65,fg+:15,bg+:239,hl+:108
  --color info:108,prompt:109,spinner:108,pointer:168,marker:168
  '
fi

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/pnezis/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/pnezis/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/pnezis/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/pnezis/google-cloud-sdk/completion.zsh.inc'; fi


# aliases
alias rmswp="find . -type f -name \"*.swp\" -exec rm -f {} \;"
