if [[ `uname` == 'Darwin' ]]; then
    PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
    MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
fi

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="pnezis"

# Comment this out to disable weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# oh-my-zsh plugins to load
plugins=(git)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

# Free up up Ctrl-S and Ctrl-Q for use with Vim:
stty -ixon -ixoff

# Set ls colors
eval `dircolors $HOME/.dircolors`

# Force tmux to assume that terminal supports 256 colors
alias tmux="tmux -2"
alias t="$HOME/dotfiles/bin/todo/todo.sh -d $HOME/dotfiles/bin/todo/todo.cfg"

# Switch to MacVim if in OsX
if [[ `uname` == 'Darwin' ]]; then
    alias vim="mvim -v"
fi

# Make vim default editor
export EDITOR="vim"

# Use Ctrl-Z to switch back to the last background job
# All credits here: http://sheerun.net/2014/03/21/how-to-boost-your-vim-productivity/?utm_source=hackernewsletter&utm_medium=email&utm_term=fav
fancy-ctrl-z () {
    if [[ $#BUFFER -eq 0 ]]; then
        BUFFER="fg"
        zle accept-line
    else
        zle push-input
        zle clear-screen
    fi
}

zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z

# Aliases
